### ISSUE TITLE
Addition for new version

### ISSUE THREAD

**Issue by deniscohen** [CoSci-LLC/KiLib-OSS#104]

**Comment by deniscohen** [comment]
- [ ] Add grain density to Constants
- [ ] Add functionality to Soil class

**Comment by deniscohen** [comment]
Question for anyone interested in helping (@haydn-jones @oparkins @ohunter ):
We have this soil class which contains data about soil physical properties.
Often, the soil property is a distribution, say for example density, represented by a mean and standard deviation (from data).
Now I need to compute another property from the density, say porosity. I can't compute it from the soil data because I don't know the exact value of the density (I only know mean and std dev, the actual value is calculated in say another piece of code).
Where should I put this new piece of code (function) that will compute the porosity from the actual value of density?
Outside of the soil class but in the Soils directory in KiLib-OSS?
Other ideas, suggestions?
The function themselves are pretty simple.
Thanks

**Comment by ohunter** [comment]
Given my current impression of the soil inheritance structure it could make sense that the base soil class implements a virtual function which can be overridden if a specific soil needs to do so. This does however bloat the classes somewhat, and comes at the cost of performance (albeit a minor one). It can also be more bug prone due to the need to do type deduction at runtime.
Another way of going at it would be to use a free function. This doesn't introduce bloat to the class hierarchy, but makes it harder to implement custom behavior for specific types of soil.
A third way of doing it would be to have another abstraction layer on top of the soils. This class/struct would act as a store of the computed values. In order to specialize the computation for a type of soil you would just specialize the property function itself for that class.

Personally I prefer the 3rd approach as it also works better with the future of template programming in C++, but that is only somewhat relevant.
