### ISSUE TITLE
CMake is really ugly

### ISSUE THREAD

**Issue by haydn-jones** [CoSci-LLC/KiLib-OSS#7]

**Comment by oparkins** [comment]
- [ ] Add Subdirectories for cmake files
- [ ] Remove install code

**Comment by oparkins** [comment]
I have worked on this in branch issue7. How ugly is it now? What do you think could be cleaned up more?

**Comment by haydn-jones** [comment]
Look a lot more manageable now. Is the install interface stuff still needed?
![image](https://user-images.githubusercontent.com/9584084/102702452-15f9a100-4220-11eb-8391-8fc6da5f984b.png)

**Comment by oparkins** [comment]
Nope, we don't need it. Just updated this in 5721221afbe6d

**Comment by oparkins** [comment]
One more thing to add:
- [ ] Add Debug vs Release compiler defines
- [ ] Add SPDLOG_DEBUG to debug statements

**Comment by oparkins** [comment]
Just pushed the fixed the previous items in bfd57e3842f0954f6a98a5ecd8c10b1897e9bc25. Now when you add `-DCMAKE_BUILD_TYPE=Debug` to your cmake line, it will build with the proper `SPDLOG_ACTIVE_LEVEL` set to `1` (debug).

Now a warning - you will still have to call `spdlog::set_level(spdlog::level::debug);` for the debugging to work. The only difference is that when you use `SPDLOG_DEBUG` during a release build, those instructions get replaced with a `void(0);`.

**Comment by deniscohen** [comment]
So isn't it better to use `SPDLOG_DEBUG` everywhere in KiLib-OSS (and KiLib)? Keep `spdlog::set_level(spdlog::level::debug);` for main programs that use KiLib?

**Comment by oparkins** [comment]
Yup. It is. A good, simple example is `KiLib.test`. It still tells the logger to set the debug level appropriately. That way KiLib can have the debug functionality modified by both the building and the requested operation of the main programs that use it. 

The previous comment was from my lack of knowledge/documentation of spdlog. It was annoying me because I was adding the proper flags, but it still wasn't outputting any debug statements in the test program. Then I figured out that both the define and the logger level have to be set for everything to work properly. I wanted to document that feature of spdlog before I forgot haha.

**Comment by deniscohen** [comment]
ok so something to be done for all tests in both KiLib-OSS and KiLib. Thanks

**Comment by oparkins** [comment]
Yup. I've just made a pull request (https://github.com/CoSci-LLC/KiLib-OSS/pull/9) for this. I figured we can also add any other features people have been working on before merging it.
